const en={
  appSubtitle:'Sparse constraints · Context-aware correction',documentTitle:'Prism — Photo Color Correction',workspace:'WORKSPACE',undo:'Undo · Ctrl Z',redo:'Redo · Ctrl Y',openProject:'Open project',saveProject:'Save project',export:'Export',noImage:'No image',untitledPhoto:'Untitled photo',pipelineCurrent:'Current pipeline',projectFileName:'prism-project',copySuffix:'copy',photoViewLabel:'{view} photo view',workingColorSpace:'LINEAR sRGB · OKLab',webglPreview:'WEBGL2 PREVIEW',
  languageSwitch:'中文',headerActions:'Language and help',help:'Help',helpTitle:'Prism quick guide',close:'Close',hintStrengthAria:'Hint strength',hintRadiusAria:'Hint radius',
  editStack:'EDIT STACK',corrections:'Corrections',correctionLayerName:'Correction {count}',createLayer:'Create correction layer',importPhoto:'Import photo',saveBeforeImport:'Save the current project before importing another photo?',noLayers:'No correction layers',noLayersHelp:'Click a color in your photo to create a correction from an original-image sample.',startFirstCorrection:'Start first correction',disableLayer:'Disable layer',enableLayer:'Enable layer',moveLayerUp:'Move layer up',moveLayerDown:'Move layer down',layerName:'Layer name',activationThumbnail:'Activation thumbnail',constraintCount:'{count} constraint{plural}',hintCount:'{count} hints',addConstraint:'Add color constraint',duplicate:'Duplicate',delete:'Delete',statusProcessing:'Processing',statusReady:'Ready',
  selectTool:'Select',panTool:'Pan the photo by dragging',addConstraintTool:'Add a constraint to selected layer',includeTool:'Include hint: click a region to strengthen activation',excludeTool:'Exclude hint: click a region to suppress activation',previewView:'Preview debug view',constraintMarkerTitle:'Constraint {count}: drag to resample original color',layerStrengthAria:'Layer strength',moveConstraintAria:'Move constraint to layer',
   viewCorrected:'Corrected',viewOriginal:'Original',viewSplit:'Before / after split',viewDifference:'Difference',viewSeed:'Selected seed field',viewActivation:'Layer activation',viewActivationOverlay:'Activation heatmap overlay',viewDistanceColor:'Color distance',viewDistanceSpatial:'Spatial distance',viewDistanceContext:'Context distance',viewDistanceEdge:'Edge distance',viewDistanceTotal:'Weighted total distance',viewDominantSeed:'Dominant seed',viewHintContribution:'Hint contribution',viewDominant:'Dominant layer',viewContribution:'Layer contribution',viewTotalCorrection:'Total correction magnitude',viewOutOfGamut:'Out of gamut',zoomOut:'Zoom out',zoomIn:'Zoom in',compare:'Compare',
  welcomeEyebrow:'PRISM COLOR WORKSPACE',welcomeTitleFirst:'Make precise corrections',welcomeTitleSecond:'with fewer controls.',welcomeText:'Sample a color, describe what it should be, and let Prism infer where that correction belongs.',choosePhoto:'Choose a photo',localFormats:'Local processing · JPEG, PNG, WebP, AVIF',sampleOriginal:'Click the image to sample its original color',includeClick:'Click to add include hint',excludeClick:'Click to add exclude hint',
  algorithmInspector:'ALGORITHM INSPECTOR',layerSettings:'Layer settings',copyLayer:'Create layer copy',selectCorrectionLayer:'Select a correction layer',inspectorEmpty:'Activation and transform diagnostics appear here once a layer is selected.',newLayer:'New layer',activationTab:'Activation',transformTab:'Transform',
  activationField:'ACTIVATION FIELD',whereApplies:'Where this correction applies',live:'LIVE',fieldEmpty:'Add a color constraint to generate its activation field',low:'LOW',high:'HIGH',targetIndependent:'Target-independent · computed from original image context only',seedFields:'SEED FIELDS',perConstraintEvidence:'Per-constraint evidence',originalSample:'original sample',confidence:'confidence',noConstraints:'No constraints yet. Use + Constraint and click the photo.',
   model:'MODEL',gaussianFeatureDistance:'Appearance Gaussian baseline',featurePreset:'Feature preset',presetSpatial:'Spatial-only',presetColor:'Color-only',presetColorXY:'Color + XY',presetColorContext:'Color + context',presetColorContextEdge:'Color + context + edge',presetCustom:'Custom weights',seedAggregator:'Seed aggregator',aggregatorOr:'Probabilistic OR',aggregatorSmoothMax:'Smooth max',colorCue:'Color cue',spatialPrior:'Spatial prior',multiScaleContext:'Multi-scale context',edgeTexture:'Edge / texture',advancedScales:'Advanced scales & kernel',colorScale:'Color scale',spatialScale:'Spatial scale',contextScale:'Context scale',edgeScale:'Edge scale',gaussianSharpness:'Gaussian sharpness',smallContextWeight:'Small-context weight',mediumContextWeight:'Medium-context weight',largeContextWeight:'Large-context weight',varianceWeight:'Variance cue weight',localContrastWeight:'Local-contrast weight',edgeTextureWeight:'Edge-texture weight',luminanceGradientWeight:'Luminance-gradient weight',chromaGradientWeight:'Chroma-gradient weight',hintSharpness:'Hint Gaussian sharpness',smallRadius:'Small context radius',mediumRadius:'Medium context radius',largeRadius:'Large context radius',hintRadius:'Hint radius',upsampleSigma:'Upsample guide σ',smoothMaxTemperature:'Smooth-max temperature',analysisResolution:'Analysis resolution',analysisDownsampling:'Analysis downsampling',areaDownsampling:'Area / box',fieldUpsampling:'Field upsampling',guidedBilinear:'Guided bilinear (2×2)',bilinear:'Bilinear',
  scopeHints:'SCOPE HINTS',lightweightHints:'Lightweight include / exclude',hintEmpty:'Add a local correction hint without painting a mask.',includeHere:'Include here',excludeHere:'Exclude here',
   sharedTransform:'SHARED COLOR TRANSFORM',oneTransformPerLayer:'One transform per layer',solved:'SOLVED',transformExplanation:'Color constraints determine Δ. Activation controls where it applies.',transformModel:'Transform model',adaptive:'Evidence-adaptive',constant:'Constant residual',affine:'Affine residual',rootPolynomial:'Centered root-polynomial',ridgeRegularization:'Ridge regularization',nonlinearRegularization:'Nonlinear regularization',advancedCapacity:'Adaptive capacity & solver bounds',minimumColorSpread:'Minimum source-color spread',minimumConstraintCount:'Minimum constraint count',affineConditionLimit:'Affine condition limit',rootConditionLimit:'Root-polynomial condition limit',affineSpreadFraction:'Affine spread fraction',conditionRegularizationBoost:'Condition regularization boost',maxPenaltyBoost:'Max adaptive penalty boost',nonlinearConditionScale:'Nonlinear condition scale',nonlinearMaxConditionBoost:'Nonlinear maximum condition boost',interceptPenaltyWeight:'Intercept penalty weight',coefficientLimit:'Coefficient limit',constraints:'CONSTRAINTS',effectiveModel:'EFFECTIVE MODEL',stability:'STABILITY',stable:'STABLE',regularized:'REGULARIZED',pending:'pending',solverDiagnostics:'SOLVER DIAGNOSTICS',condition:'CONDITION',residualNorm:'RESIDUAL NORM',colorSpread:'COLOR SPREAD',fallbackReason:'Fallback',solverDescription:'Weighted ridge coefficients use this layer’s source, target and confidence only.',colorEvidence:'COLOR EVIDENCE',constraintTargets:'Constraint targets',addConstraintsToSolve:'Add constraints to solve a shared transform.',
  selectedConstraint:'SELECTED CONSTRAINT',sourceToTarget:'Source → target',deleteSelectedConstraint:'Delete selected constraint',originalSource:'ORIGINAL SOURCE',correctionTarget:'CORRECTION TARGET',currentColorCorrect:'Current color is correct',editTargetOnly:'Editing the target re-solves the transform only. The activation seed remains unchanged.',moveConstraint:'Move constraint to layer',compositor:'COMPOSITOR',residualAdd:'Residual add · order independent',sequential:'Sequential',normalizedMixture:'Normalized mixture',gamut:'GAMUT',oklchCompression:'OKLCH chroma compression',hardClip:'Hard-clip baseline',
   compareMode:'COMPARE MODE',sameIntent:'Same user intent · independent pipeline variants',variants:'variants',architectureHooks:'ARCHITECTURE HOOKS',perPointBaseline:'Per-point independent',sharedLayerBaseline:'Shared correction layer',jointRegressionBaseline:'Joint per-pixel regression',variantMeta:'{count} layers · shared user intent',outOfGamutRate:' out of gamut',syntheticBenchmarks:'Synthetic benchmark suite',syntheticBenchmarksHelp:'Procedural ground-truth fixtures · seven scenes with cue and transform ablations',runBenchmarks:'Run benchmarks',benchmarkRunning:'Running…',
  statusLoadPhoto:'Load a photo to start a correction session.',statusImageReady:'{dimensions} · Original image analyzed on demand',statusProcessingError:'Processing error',statusRendered:'{dimensions} · {time} ms · {rate}% out of gamut',statusPreparing:'Loaded {name} · preparing analysis',statusImageImportFailed:'Image import failed',statusProjectNeedsPhoto:'Project opened · re-import the matching original photo to rebuild previews',photoDecodeError:'Could not decode the selected photo.',workerError:'Processing failed: {message}',projectOpenError:'Could not open project: {message}',
  statusReadyFooter:'Ready',presetSharedContext:'Context + edge',presetConstant:'Constant transform',presetAffine:'Affine transform',presetSequential:'Sequential compositor',presetNormalizedMixture:'Normalized mixture',presetPerPoint:'Per-point baseline',presetJoint:'Joint per-pixel baseline',
  helpIntro:'Use a few source → target samples to describe color errors. Prism estimates both the shared color transform and where it should apply.',helpStep1Title:'1 · Load a photo',helpStep1:'Choose Import photo. The image stays in this browser and is not uploaded.',helpStep2Title:'2 · Add a correction',helpStep2:'Click the image to create a layer and sample its original color. Choose a target color, or use Current color is correct to preserve a sample.',helpStep3Title:'3 · Refine the scope',helpStep3:'Select a layer and use + Constraint to add more colors to the same regime. Include / exclude hints tune activation without painting a mask. Drag a marker to resample its source from the original.',helpStep4Title:'4 · Inspect and compare',helpStep4:'Switch between Activation and Transform inspectors. Use the preview menu for difference, seed, dominant-layer, contribution and gamut views. Compare runs side by side with the same user intent.',helpStep5Title:'5 · Save or export',helpStep5:'Save a .prism.json project to keep editing intent and settings. Re-import the matching original photo when reopening. Export writes the corrected image as PNG.',helpShortcuts:'Keyboard shortcuts',helpUndo:'Ctrl/Cmd + Z · Undo',helpRedo:'Ctrl/Cmd + Shift + Z or Ctrl/Cmd + Y · Redo',helpResearchNote:'The Gaussian Activation and transform-capacity thresholds are experimental defaults. Use Compare Mode and the algorithm inspectors to evaluate alternatives.',
} as const

const zh:Record<keyof typeof en,string>={
  appSubtitle:'稀疏约束 · 上下文校色',documentTitle:'Prism — 照片颜色校正',workspace:'工作区',undo:'撤销 · Ctrl Z',redo:'重做 · Ctrl Y',openProject:'打开项目',saveProject:'保存项目',export:'导出',noImage:'未导入照片',untitledPhoto:'未命名照片',pipelineCurrent:'当前算法配置',projectFileName:'Prism-校正项目',copySuffix:'副本',photoViewLabel:'{view}照片预览',workingColorSpace:'工作色彩空间：线性 sRGB · OKLab',webglPreview:'WebGL2 预览',
  languageSwitch:'English',headerActions:'语言与帮助',help:'帮助',helpTitle:'Prism 使用说明',close:'关闭',hintStrengthAria:'提示强度',hintRadiusAria:'提示半径',
  editStack:'校正图层',corrections:'颜色校正',correctionLayerName:'校正图层 {count}',createLayer:'新建校正图层',importPhoto:'导入照片',saveBeforeImport:'导入另一张照片前，是否保存当前项目？',noLayers:'还没有校正图层',noLayersHelp:'点击照片中的颜色，从原图采样并创建校正。',startFirstCorrection:'开始第一次校正',disableLayer:'关闭图层',enableLayer:'启用图层',moveLayerUp:'图层上移',moveLayerDown:'图层下移',layerName:'图层名称',activationThumbnail:'作用场预览',constraintCount:'{count} 条颜色约束',hintCount:'{count} 个范围提示',addConstraint:'添加颜色约束',duplicate:'复制',delete:'删除',statusProcessing:'处理中',statusReady:'就绪',
  selectTool:'选择',panTool:'拖动平移照片',addConstraintTool:'向当前图层添加颜色约束',includeTool:'包含提示：点击区域以增强作用强度',excludeTool:'排除提示：点击区域以减弱作用强度',previewView:'预览与调试视图',constraintMarkerTitle:'约束 {count}：拖动后从原图重新采样颜色',layerStrengthAria:'图层强度',moveConstraintAria:'移动约束到图层',
   viewCorrected:'校正结果',viewOriginal:'原图',viewSplit:'前后分屏',viewDifference:'差异图',viewSeed:'选中约束的作用场',viewActivation:'图层聚合作用场',viewActivationOverlay:'作用场热度叠加',viewDistanceColor:'颜色距离',viewDistanceSpatial:'空间距离',viewDistanceContext:'上下文距离',viewDistanceEdge:'边缘距离',viewDistanceTotal:'加权总距离',viewDominantSeed:'主导约束种子',viewHintContribution:'范围提示贡献',viewDominant:'主导图层',viewContribution:'图层贡献量',viewTotalCorrection:'总校正幅度',viewOutOfGamut:'超出色域区域',zoomOut:'缩小',zoomIn:'放大',compare:'对比实验',
  welcomeEyebrow:'PRISM 照片颜色校正',welcomeTitleFirst:'少量约束，精准校色',welcomeTitleSecond:'让颜色校正更简单。',welcomeText:'采样一种颜色，指定它应该呈现的颜色，Prism 会推断校正应作用的位置。',choosePhoto:'选择照片',localFormats:'本地处理 · JPEG、PNG、WebP、AVIF',sampleOriginal:'点击照片以采样原图颜色',includeClick:'点击添加包含提示',excludeClick:'点击添加排除提示',
  algorithmInspector:'算法检查器',layerSettings:'图层设置',copyLayer:'复制校正图层',selectCorrectionLayer:'选择一个校正图层',inspectorEmpty:'选择图层后，这里会显示作用场与颜色变换诊断。',newLayer:'新建图层',activationTab:'作用场',transformTab:'颜色变换',
  activationField:'作用强度场',whereApplies:'此校正在哪里生效',live:'实时',fieldEmpty:'添加颜色约束以生成作用场',low:'弱',high:'强',targetIndependent:'与目标颜色解耦 · 仅由原图上下文计算',seedFields:'约束作用种子',perConstraintEvidence:'每条约束的独立作用场',originalSample:'原图采样',confidence:'置信度',noConstraints:'还没有颜色约束。点击“+ 约束”后再点击照片。',
   model:'模型',gaussianFeatureDistance:'外观高斯基线',featurePreset:'特征预设',presetSpatial:'仅空间',presetColor:'仅颜色',presetColorXY:'颜色 + 位置',presetColorContext:'颜色 + 上下文',presetColorContextEdge:'颜色 + 上下文 + 边缘',presetCustom:'自定义权重',seedAggregator:'种子聚合策略',aggregatorOr:'概率 OR',aggregatorSmoothMax:'平滑最大值',colorCue:'颜色线索',spatialPrior:'空间先验',multiScaleContext:'多尺度上下文',edgeTexture:'边缘 / 纹理',advancedScales:'高级尺度与核参数',colorScale:'颜色尺度',spatialScale:'空间尺度',contextScale:'上下文尺度',edgeScale:'边缘尺度',gaussianSharpness:'高斯锐度',smallContextWeight:'小尺度上下文权重',mediumContextWeight:'中尺度上下文权重',largeContextWeight:'大尺度上下文权重',varianceWeight:'局部方差权重',localContrastWeight:'局部对比度权重',edgeTextureWeight:'边缘纹理权重',luminanceGradientWeight:'亮度梯度权重',chromaGradientWeight:'色度梯度权重',hintSharpness:'范围提示锐度',smallRadius:'小尺度上下文半径',mediumRadius:'中尺度上下文半径',largeRadius:'大尺度上下文半径',hintRadius:'提示半径',upsampleSigma:'上采样引导 σ',smoothMaxTemperature:'平滑最大值温度',analysisResolution:'分析分辨率',analysisDownsampling:'分析图缩小策略',areaDownsampling:'面积 / 盒式采样',fieldUpsampling:'作用场上采样',guidedBilinear:'引导双线性（2×2）',bilinear:'双线性',
  scopeHints:'作用范围提示',lightweightHints:'轻量包含 / 排除提示',hintEmpty:'添加局部提示，无需绘制精确蒙版。',includeHere:'在此包含',excludeHere:'在此排除',
   sharedTransform:'图层共享颜色变换',oneTransformPerLayer:'每个图层使用一个共享变换',solved:'已求解',transformExplanation:'颜色约束决定 Δ；Activation 决定它在哪里生效。',transformModel:'变换模型',adaptive:'按证据自适应',constant:'常量残差',affine:'仿射残差',rootPolynomial:'中心化根多项式',ridgeRegularization:'岭回归正则化',nonlinearRegularization:'非线性正则化',advancedCapacity:'自适应容量与求解边界',minimumColorSpread:'最小颜色覆盖范围',minimumConstraintCount:'最少约束数量',affineConditionLimit:'仿射条件数上限',rootConditionLimit:'根多项式条件数上限',affineSpreadFraction:'仿射覆盖比例',conditionRegularizationBoost:'条件数正则增强',maxPenaltyBoost:'最大自适应惩罚',nonlinearConditionScale:'非线性条件尺度',nonlinearMaxConditionBoost:'非线性最大条件增强',interceptPenaltyWeight:'截距惩罚权重',coefficientLimit:'系数幅度上限',constraints:'约束数量',effectiveModel:'实际模型',stability:'数值稳定性',stable:'稳定',regularized:'已加强正则',pending:'等待计算',solverDiagnostics:'求解器诊断',condition:'条件数',residualNorm:'残差范数',colorSpread:'颜色覆盖',fallbackReason:'回退原因',solverDescription:'加权岭回归仅使用本图层的 source、target 与 confidence。',colorEvidence:'颜色证据',constraintTargets:'约束目标颜色',addConstraintsToSolve:'添加颜色约束以求解共享变换。',
  selectedConstraint:'选中约束',sourceToTarget:'原始颜色 → 目标颜色',deleteSelectedConstraint:'删除选中约束',originalSource:'原图颜色',correctionTarget:'校正目标',currentColorCorrect:'当前颜色正确',editTargetOnly:'修改目标只会重新求解颜色变换，不会改变 Activation Seed。',moveConstraint:'移动约束到图层',compositor:'图层合成',residualAdd:'残差相加 · 不依赖顺序',sequential:'顺序合成',normalizedMixture:'归一化混合',gamut:'色域映射',oklchCompression:'OKLCH 色度压缩',hardClip:'硬裁切基线',
   compareMode:'对比实验',sameIntent:'共享用户意图 · 独立算法配置',variants:'个方案',architectureHooks:'架构基线',perPointBaseline:'逐点独立图层',sharedLayerBaseline:'共享校正图层',jointRegressionBaseline:'逐像素联合回归',variantMeta:'{count} 个图层 · 共享用户意图',outOfGamutRate:' 超出色域',syntheticBenchmarks:'合成基准测试',syntheticBenchmarksHelp:'程序生成且有 ground truth · 七类场景并比较特征线索与变换模型',runBenchmarks:'运行基准测试',benchmarkRunning:'运行中…',
  statusLoadPhoto:'导入照片以开始校正。',statusImageReady:'{dimensions} · 已载入原图，可开始编辑',statusProcessingError:'处理出错',statusRendered:'{dimensions} · {time} 毫秒 · {rate}% 超出色域',statusPreparing:'已载入 {name} · 正在准备分析',statusImageImportFailed:'照片导入失败',statusProjectNeedsPhoto:'项目已打开 · 请重新导入对应原图以重建预览',photoDecodeError:'无法解码所选照片。',workerError:'图像处理失败：{message}',projectOpenError:'无法打开项目：{message}',
  statusReadyFooter:'就绪',presetSharedContext:'颜色 + 上下文 + 边缘',presetConstant:'常量变换',presetAffine:'仿射变换',presetSequential:'顺序合成',presetNormalizedMixture:'归一化混合',presetPerPoint:'逐点独立基线',presetJoint:'逐像素联合基线',
  helpIntro:'用少量 source → target 颜色样本描述照片中的颜色误差。Prism 会估计共享颜色变换，以及这项校正应作用的位置。',helpStep1Title:'1 · 导入照片',helpStep1:'点击“导入照片”选择本地图片。图像留在当前浏览器中，不会上传。',helpStep2Title:'2 · 添加校正约束',helpStep2:'点击照片创建图层并采样原图颜色，然后选择目标颜色；也可用“当前颜色正确”保留该颜色。',helpStep3Title:'3 · 调整作用范围',helpStep3:'选中图层后点击“+ 约束”，可向同一校正方案添加更多颜色。包含 / 排除提示能微调作用场，无需绘制蒙版。拖动约束标记会从原图重新采样 source。',helpStep4Title:'4 · 检查并比较',helpStep4:'在右侧切换“作用场”和“颜色变换”检查器。预览菜单可查看差异、Seed、主导图层、贡献量与色域视图。Compare 可用同一组用户意图并排比较算法。',helpStep5Title:'5 · 保存或导出',helpStep5:'保存 .prism.json 项目以保留编辑意图和参数。重新打开时需要导入对应原图。导出会生成校正后的 PNG。',helpShortcuts:'键盘快捷键',helpUndo:'Ctrl/Cmd + Z · 撤销',helpRedo:'Ctrl/Cmd + Shift + Z 或 Ctrl/Cmd + Y · 重做',helpResearchNote:'高斯 Activation 与自适应阈值是实验默认值。可用 Compare Mode 和算法检查器比较不同策略。',
}

export type Locale='en'|'zh'
export type TranslationKey=keyof typeof en
export const translations={en,zh}
